# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AgspCVaEWcv0rQssAQ3ClAgPTHnrHTfx
"""

import numpy as np
from numpy.random import random
import matplotlib.pyplot as plt
from scipy import misc # contain a immage of racoon
from PIL import Image # for reading image files

my_array = np.array([1.1, 9.2,8.1, 4.7])
my_array.shape

my_array[2]

my_array.ndim

array_2d=np.array([[1,2,3,9],[5,6,7,8]])

print(f"array_2d has {array_2d.ndim} dimentions")
print(f"It's shape is: {array_2d.shape}")
print(f"It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns")
print(array_2d)

array_2d[1,2]

array_2d[0,:]

mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],
                          
                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])

mystery_array.ndim

mystery_array.shape
print(f'We have {mystery_array.ndim} dimensions')
print(f'The shape is {mystery_array.shape}')



mystery_array[2,1,3]

mystery_array[2,1,:]

mystery_array[:,:,0]

a=np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28])

np.average(a)

a[-3:]

a[2:5]

a[12:]

a[::2]

np.flip(a)

b = np.array([6,0,9,0,0,5,0])
nz_indices = np.nonzero(b)
nz_indices # note this is a tuple

rng = np.random.default_rng(12345)
rng

random = random((3,3,3))
random

x = np.linspace(start=0, stop=100, num=9)
x

y = np.linspace(start=-3, stop=3, num=9)
y

plt.plot(x,y)
plt.show()

noise = np.random.random((128,128,3))
print(noise.shape)
plt.imshow(noise)

v1 = np.array([4,5,2,7])
v2 = np.array([2,1,3,3])
v1 + v2

v1 * v2

v1 / v2

array_2d = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8]])

array_2d + 10

array_2d * 5

a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])
 
b1 = np.array([[4, 1, 3],
               [5, 8, 5]])

c = np.matmul(a1,b1)
c

img = misc.face()

plt.imshow(img)

img.shape

type(img)

img.ndim

grayinization=img / 255
grey_vals = np.array([0.2126, 0.7152, 0.0722])
grayinization = grayinization @ grey_vals 
grayinization = np.flip( grayinization)
plt.imshow(grayinization, cmap='gray')

img = np.flip(np.rot90(img))
plt.imshow(img)

RGB_img = img/255
rev_img = 255 - img
plt.imshow(rev_img)

mi_img = Image.open('yummy_macarons.jpg')

mi_img

img_array = np.array(mi_img)

img_array.ndim

img_array.shape

plt.imshow(255-img_array)